
server:
  port: 8081
  shutdown: graceful
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown


spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/orderService?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: hasan
    password: hasan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

  
  
