
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone : http://eureka:password@localhost:8761/eureka/



server:
  port: 0
  shutdown: graceful
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    beans:
      enable: false
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true


spring:
  application:
    name: INVENTORY-SERVICE
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/productService?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: hasan
    password: hasan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true


resilience4j:
  timelimiter:
    instances:
      inventory:
        timeout-duration: 10s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
  ratelimiter:
    metrics:
      enabled: true
    instances:
      inventory:
        register-health-indicator: true
        limit-for-period: 2
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50

